# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dates in R
email: matthew.pettis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Discussion of dates and times in R.
baseurl: "" # the subpath of your site, e.g. /blog
#baseurl: "/r-dates_talk" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
url: "http://mpettis.github.io" # the base hostname & protocol for your site
twitter_username: mtpettis
github_username:  mpettis

# Build settings
markdown: kramdown

